### PR TITLE
Add i18n support

### PR DESCRIPTION
**Pull request by rbuj**
Test: Catalan locale
```
$ LANG=ca.UTF-8 caja-dropbox update
``` 
Screenshot:

Screenshot at 2021-02-08 02-19-46

### CODE REVIEW

**Comment by raveit65** [comment]
I got Catalan locale at
```
[rave@mother ~]$ ls /usr/local/share/locale/ca/LC_MESSAGES
caja-dropbox.mo
```
But it is in English.
```
[rave@mother ~]$ LANG=ca.UTF-8 /usr/local/bin/caja-dropbox update

(caja-dropbox:67925): Gtk-WARNING **: 20:07:31.360: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/local/bin/caja-dropbox:459: PyGTKDeprecationWarning: Stock items are deprecated. Please use: Gtk.Button.new_with_mnemonic(label)
  self.ok = ok = Gtk.Button(stock=Gtk.STOCK_OK)
/usr/local/bin/caja-dropbox:464: PyGTKDeprecationWarning: Stock items are deprecated. Please use: Gtk.Button.new_with_mnemonic(label)
  cancel = Gtk.Button(stock=Gtk.STOCK_CANCEL)
```
Still wondering what is wrong?

**Comment by raveit65** [comment]
Ok, it works well when i install To /usr.

**Comment by rbuj** [comment]
I translated the `ca.po` file locally for testing the internationalization.

**Comment by rbuj** [comment]
You need to install the Catalan langpack otherwise it fails back to C locale on Fedora:
```
$ sudo dnf install -y langpacks-ca -y
```

**Comment by raveit65** [comment]
All is working when i install to /usr.
I think using caja extension lib  in /usr and installing an extension to /usr/local doesn't work very well.
I just added caja-dropbox to transifex.
All done :)

**Pull request merged**
