### PR TITLE
show full path of caja-extension-dir

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by monsta** [comment]
Hmm... I'm confused. Why doesn't it expand the `${prefix}` part now?
It should show `/usr` instead (I've checked it did so at commit 285937d893afae5874c483a59d91e035211a7f56)...
```
checking for caja extension directory... ${prefix}/lib/x86_64-linux-gnu/caja/extensions-2.0
```

**Comment by yetist** [comment]
I can't give you the answer, it should show `/usr` instead of `${prefix}`, but it doesn't.

Guess is related to 'autogen.sh && make && make distcheck`, no prefix is specified.

In any case, the result is always right. Whether it is distcheck, --prefix or --with-caja-extension-dir.

I can't make it any better, maybe other one can try it.

**Comment by vkareh** [comment]
autoconf doesn't expand nested variables... in this case, you have the following situation:
* `$libdir` expands to `${exec_prefix}/lib64` (in my system, the `lib*` part will be different)
* `$exec_prefix` expands to `${prefix}`
* `$prefix` expands to `NONE`

Which means that you would need to do multiple expansions. The project provides a macro extension to initialize these variables: [ax_expand_prefix](https://www.gnu.org/software/autoconf-archive/ax_expand_prefix.html), which essentially executes:
```bash
    test "x$prefix" = xNONE && prefix=$ac_default_prefix
    test "x$exec_prefix" = xNONE && exec_prefix='${prefix}'
```
You're still left with the task of doing the recursive expansion. As per the extension's documentation, you'd need to do something like:
```bash
    libdir=$(eval "echo \"$libdir\"")
    libdir=$(eval "echo \"$libdir\"")
```
Doing these things will result in the message properly expanding (I get `checking for caja extension directory... /usr/lib64/caja/extensions-2.0`). But seems like an overkill for a configure message. This is an issue in autoconf, not in our repo. I would honestly just leave it as is

**Comment by yetist** [comment]
Rebase on master, and use a new variable to save system path and show, please test.

**Pull request merged**
