### PR TITLE
caja-dropbox: reset_all_files is a static function

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Can you explain why this is better?

**Comment by rbuj** [comment]
The function `gboolean reset_all_files (CajaDropbox *cvs)` is only used in the `caja-dropbox.c` file.
```
$ git grep reset_all_files
src/caja-dropbox.c:reset_all_files(CajaDropbox *cvs) {
src/caja-dropbox.c:  g_idle_add((GSourceFunc) reset_all_files, cvs);
src/caja-dropbox.c:  reset_all_files(cvs);
src/caja-dropbox.c:  reset_all_files(cvs);
```
It removes the warning below:
```
caja-dropbox.c:111:1: warning: no previous prototype for ‘reset_all_files’ [-Wmissing-prototypes]
  111 | reset_all_files(CajaDropbox *cvs) {
      | ^~~~~~~~~~~~~~~
```

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
Understand.

**Pull request merged**
