### PR TITLE
Back ports

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Leaving this one for others, as I don't have this installed nor a Dropbox account

**Comment by monsta** [comment]
I have caja-dropbox only in one VM for testing purposes, so I was able to test some parts of this... "Validate that Dropbox runs after downloading it" works, new `dropbox update` command works.

No idea how to test "Display link url on status" and python-gpg stuff.

@sunweaver: maybe you could help us with testing this? This PR also includes a few fixes that are currently in Debian/Ubuntu patches.

**Comment by sunweaver** [comment]
Hi,

On Saturday, 5 January 2019, monsta wrote:
> I have caja-dropbox only in one VM for testing purposes, so I was able to test some parts of this... "Validate that Dropbox runs after downloading it" works, new `dropbox update` command works.
> 
> No idea how to test "Display link url on status" and python-gpg stuff.
> 
> @sunweaver: maybe you could help us with testing this? This PR also includes a few fixes that are currently in Debian/Ubuntu patches.
> 

(un)Fortunately, I don't have a Dropbox account and I am not really willing to get one.

@gnugr: you previously did functionality testings, could you?
-- 
Sent from my Sailfish device

**Comment by raveit65** [comment]
@sunweaver @monsta 
python-gpg commit is for and from debian, see original commit message
https://github.com/dropbox/nautilus-dropbox/commit/e936720
It is just a simple replacement.
Forget was this guy said about fedora........
.... of course fedora ships python2-gpg ;)

> I don't have a Dropbox account and I am not really willing to get one.

sigh, perhaps i should say the same if i test software for you which i don't use for myself
... thanks for your help :P

**Comment by gnugr** [comment]
Hi,

Στις 5/1/19 7:21 μ.μ., ο Mike Gabriel έγραψε:
> Hi,
>
> On Saturday, 5 January 2019, monsta wrote:
> > I have caja-dropbox only in one VM for testing purposes, so I was
> able to test some parts of this... "Validate that Dropbox runs after
> downloading it" works, new `dropbox update` command works.
> >
> > No idea how to test "Display link url on status" and python-gpg stuff.
> >
> > @sunweaver: maybe you could help us with testing this? This PR also
> includes a few fixes that are currently in Debian/Ubuntu patches.
> >
>
> (un)Fortunately, I don't have a Dropbox account and I am not really
> willing to get one.
>
> @gnugr: you previously did functionality testings, could you?
> -- 
> Sent from my Sailfish device 

Yes, i tested that past time, but Dropbox was filling my 4GB Ram badly,
and i had to remove it,

the fact is it worked perfect, sorry i don't intend to use it again
because it causes that issue

to me.

Greets

gnugr

**Comment by raveit65** [comment]
@monsta 
Can you approve please or are more tests required?
I don't think that anybody else will review this :/
And i have prepared some more commits local.

**Comment by monsta** [comment]
Ah wait, I used it incorrectly... I need to specify either `add` or `remove` argument.

```
monsta@jessica:~$ caja-dropbox exclude add ~/Dropbox/тест
Excluded: 
Dropbox/тест
monsta@jessica:~$ caja-dropbox exclude
Excluded: 
Dropbox/тест
monsta@jessica:~$ caja-dropbox exclude remove ~/Dropbox/тест
No longer excluded: 
Dropbox/тест
monsta@jessica:~$ caja-dropbox exclude
No directories are being ignored.
```
Ok, so it works, no problem here. The issue I've found is separate from this PR.

**Comment by raveit65** [comment]
Thanks for the review.

**Comment by monsta** [comment]
In the meanwhile, I've fixed `UnicodeWarning` in https://github.com/mate-desktop/caja-dropbox/commit/55e4f9b9e8b8ece3c8a25d108dde5ebdf9aef397.

**Pull request merged**
